### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by ibnesayeed** [DarkAngelZT/CarbonDate#8]
Recent Linux operating systems have started shipping with Python 3 now. Python 2 is reaching its extended EOL. Unless, it is too much work, I would suggest to go for the Python 3 support.

**Comment by DarkAngelZT** [comment]
Most of my code works in python 3, except the print line

**Comment by ibnesayeed** [comment]
Are all dependencies ready for Py3? If so, you should seriously think about supporting just Python 3 and drop support of Py2. There is a tool called [2to3](https://docs.python.org/2/library/2to3.html) that you can use to get started with all those print statement conversions.

**Comment by DarkAngelZT** [comment]
bad news:
I converted the code from 2 to 3, and it cause fatal compatibility error on beautiful soup. (previously works fine on python2 )
So no more python 3.

**Comment by ibnesayeed** [comment]
You need to use `beautifulsoup4`, earlier version of BS won't work with Python 3.
1. http://stackoverflow.com/questions/24962876/getting-error-while-using-pip
2. http://stackoverflow.com/questions/30140034/beautifulsoup-invalid-syntax-in-python-3-4-after-2to3-py

**Comment by DarkAngelZT** [comment]
The bs i'm using is bs4.

**Comment by ibnesayeed** [comment]
Then you need to track down specific API changes in the BS that are cause your specific functions to fail. Just track down the places where it is failing and search for the errors you are getting. 2to3 is not a silver bullet tool, it does help a lot though, then from there you can find the recommendations on the 2to3 documentation to make manual changes.

**Comment by DarkAngelZT** [comment]
I tried to build a docker image and run in docker. Then my python 3 code runs smoothly. It seems package conflict in my computer affect the code test. 
Now welcome to python 3 :P

**Comment by DarkAngelZT** [comment]
But the script on heroku is still py2, I'm not sure if they support py3.

**Comment by ibnesayeed** [comment]
> But the script on heroku is still py2, I'm not sure if they support py3.

@DarkAngelZT [Heroku does support the latest stable release of Python 3.x](https://devcenter.heroku.com/articles/python-runtimes#supported-python-runtimes). However, it's not defaults I guess, so you will have to include the `runtime.txt` file. Congratulations on bringing the Python 3 support b the way. :+1:

**Comment by DarkAngelZT** [comment]
Python 3 server is online now
